### ISSUE TITLE
package.json Node 6

### ISSUE THREAD

**Issue by Trejjam** [visionappscz/bootstrap-ui#106]
Hi,

it is necesery restrict library on Node v6?

**Comment by mbohal** [comment]
Not at all.

In docker we already use version 7.
https://github.com/visionappscz/bootstrap-ui/blob/master/docker/grunt/Dockerfile#L4

**Comment by adamkudrna** [comment]
We decided to upgrade Node to version 8 in #113. Thank you for your contribution!
