### ISSUE TITLE
Select2 CSS missing in dist directory

### ISSUE THREAD

**Issue by mbohal** [visionappscz/bootstrap-ui#129]
Im using BUI as documented [here](http://docs.bootstrap-ui.com/index.html#usage).

However it seems that select2 elements are missing some CSS. They are nor responsive nor pretty. See screen.
![selection_001](https://user-images.githubusercontent.com/4589176/50829457-e90a9700-1344-11e9-88e2-6ffe78edb5c0.png)

**Comment by adamkudrna** [comment]
I tested the case following the instructions in the docs and it seems to be alright, please check [my CodePen](https://codepen.io/adamkudrna/pen/NoWXmy). You will find the libraries used under the cog icon.

I noticed two possible causes in your code, though (not provided here):

1. `select2.css` is [not necessary, maybe even desired](http://docs.bootstrap-ui.com/index.html#css):
  ```html
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Titillium+Web:400,300,700&amp;subset=latin,latin-ext" type="text/css" />
        <link rel="stylesheet" href="/css/bootstrap-ui.min.css" type="text/css" />
        <link rel="stylesheet" href="/css/select2.css" type="text/css" />
  ```
2. `select2.min.js` [should precede](http://docs.bootstrap-ui.com/index.html#javascript) `bootstrap-ui.min.js`:
  ```html
    <script src="/js/jquery.min.js"></script>
    <script src="/js/moment-with-locales.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-ui.min.js"></script>
    <script src="/js/select2.min.js"></script>
  ```

So I suggest to check the usage instructions once again – minding the details –, check the versions installed and the HTML of your `select`s.
