### ISSUE TITLE
Styleguide is generated but the process does not terminate

### ISSUE THREAD

**Issue by adamkudrna** [visionappscz/bootstrap-ui#69]
Styleguide is successfully generated with message "Style guide build completed successfully!" but the process does not terminate and must be cancelled manually.

Issue in upstream: kss-node/grunt-kss#10

**Comment by adamkudrna** [comment]
Until this is fixed, distribution package must be generated in more steps when releasing a new version:

```
$ grunt build
$ grunt copy:dist && grunt copy:fonts
```

**Comment by crishpeen** [comment]
Suggested solution is to downgrade to v4 where function kss() has callback.

Source: https://github.com/kss-node/grunt-kss/issues/8

**Comment by adamkudrna** [comment]
> The --template option was replaced with --builder in kss-node 3. **Custom templates will need significant updating** for them to work as custom builders with kss-node 3.

We already made the significant update…

**Comment by crishpeen** [comment]
Fixed in https://github.com/visionappscz/grunt-kss waiting for upstream to merge pull request

**Comment by adamkudrna** [comment]
Can we switch back to upstream and close this one?

**Comment by adamkudrna** [comment]
@crishpeen: Can we switch back to upstream and close this one?
