### ISSUE TITLE
Sortable table should be aware of digraph “Ch”

### ISSUE THREAD

**Issue by adamkudrna** [visionappscz/bootstrap-ui#86]
Preconditions:

* browser supports locale
* locale is cs_CZ (also see [other languages using the digraph “ch”](https://en.wikipedia.org/wiki/Ch_(digraph)))
* string list contains strings starting with digraph “ch” (also see [other digraphs](https://en.wikipedia.org/wiki/Digraph_(orthography)))

Expected result:

* strings starting with “ch” should be grouped (this works)
* anchor “Ch” should be created in navigation (only “C” is created)

**Comment by mbohal** [comment]
The name of the group and of the anchor is taken from the `data-sort-group` attribute on the relevant `<td>`. The solution is therefore to use "Ch" instead of "C" as the value of this attribute where appropriate.
