### ISSUE TITLE
Height 100% in body.site causes bugs in android browser

### ISSUE THREAD

**Issue by crishpeen** [visionappscz/bootstrap-ui#92]
Android browser interprets height 100% similar to 100vh causing sticky footer to not stick of bottom of page but render at bottom of screen. 

However body.site has to have a set height because of IE 10 & 11 bug and it won't be fixed ([source](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview)).

**Comment by crishpeen** [comment]
One of proposed solutions is to set specific @media for only one type of browser. e.g. 
`.site {
    height: auto;
}

@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .site {
        height: 100%;
    }
}`

This solution works, but isn't nice.

**Comment by adamkudrna** [comment]
Thank you for research! Can we fix it following [Philip Walton's solution](https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css)?

**Comment by adamkudrna** [comment]
Fixed in PR #93.
